# Generated by Django 4.2.7 on 2023-11-29 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clasificacionEdad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('anioLanzamiento', models.DateField()),
                ('clasificacionEdad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.clasificacionedad')),
            ],
        ),
        migrations.CreateModel(
            name='generos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precioMensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calidadVideo', models.CharField(max_length=50)),
                ('resolucion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantTemporadas', models.IntegerField()),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.contenido')),
            ],
        ),
        migrations.CreateModel(
            name='tipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_Usuario',
            },
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=255, unique=True)),
                ('contrasena', models.CharField(max_length=50)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('tipoUsuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Visualizaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaVisualizacion', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.contenido')),
                ('usuarioId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='ValoracionesContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.IntegerField()),
                ('comentario', models.TextField()),
                ('fechaValoracion', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.contenido')),
                ('usuarioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='temporadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('anoDeEstreno', models.DateField()),
                ('cantEpisodios', models.IntegerField()),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.series')),
            ],
        ),
        migrations.CreateModel(
            name='telefonos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=8)),
                ('usuarioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='subtitulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.idioma')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSessiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHoraInSesion', models.DateTimeField(auto_now_add=True)),
                ('usuarioId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Popularidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadVisualizaciones', models.IntegerField(default=0)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.contenido')),
            ],
        ),
        migrations.CreateModel(
            name='Playlists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreLista', models.CharField(max_length=50)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.contenido')),
                ('usuarioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fechaDeNacimiento', models.DateField()),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.pais')),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.rol')),
            ],
        ),
        migrations.CreateModel(
            name='perfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.IntegerField()),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.contenido')),
            ],
        ),
        migrations.CreateModel(
            name='ListaReproduccionContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreLista', models.CharField(max_length=50)),
                ('usuarioId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='lista_contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.contenido')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.listareproduccioncontenido')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialVisualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaVisualizacion', models.DateTimeField(auto_now_add=True)),
                ('duracionVisualizacion', models.DecimalField(decimal_places=2, max_digits=4)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.contenido')),
                ('usuarioId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroDeTarjeta', models.CharField(max_length=16)),
                ('fechaDeVencimiento', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('nombreEnLaTarjeta', models.CharField(max_length=50)),
                ('usuarioId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='EstudiosProductoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('anoDeFundacion', models.IntegerField()),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.pais')),
            ],
        ),
        migrations.CreateModel(
            name='episodios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroEpisodio', models.IntegerField()),
                ('tituloEpisodio', models.CharField(max_length=50)),
                ('duracion', models.IntegerField()),
                ('anoLanzamiento', models.DateField()),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.temporadas')),
            ],
        ),
        migrations.CreateModel(
            name='DescargasOffline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDescarga', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.contenido')),
                ('usuarioId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='contenido_subtitulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.contenido')),
                ('idioma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.idioma')),
            ],
        ),
        migrations.CreateModel(
            name='contenido_idiomas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.contenido')),
                ('idioma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.idioma')),
            ],
        ),
        migrations.CreateModel(
            name='contenido_generos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.contenido')),
                ('generos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.generos')),
            ],
        ),
        migrations.AddField(
            model_name='contenido',
            name='idiomaOriginal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.idioma'),
        ),
    ]
