# Generated by Django 4.2.7 on 2023-11-26 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_clasificacionedad_generos_peliculas_and_more'),
        ('projects', '0002_usuario'),
    ]

    operations = [
    ]
