# Generated by Django 4.2.7 on 2023-11-26 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_merge_20231126_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActoresYActrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fechaDeNacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Directores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fechaDeNacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='episodios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroEpisodio', models.IntegerField()),
                ('tituloEpisodio', models.CharField(max_length=50)),
                ('duracion', models.IntegerField()),
                ('anoLanzamiento', models.DateField()),
                ('serieId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.series')),
            ],
        ),
        migrations.CreateModel(
            name='EstudiosProductoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('anoDeFundacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroDeTarjeta', models.CharField(max_length=16)),
                ('fechaDeVencimiento', models.DateField()),
                ('cvv', models.CharField(max_length=4)),
                ('nombreEnLaTarjeta', models.CharField(max_length=50)),
                ('usuarioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precioMensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calidadVideo', models.CharField(max_length=50)),
                ('resolucion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Playlists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreLista', models.CharField(max_length=50)),
                ('usuarioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='series_generos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.generos')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.series')),
            ],
        ),
        migrations.CreateModel(
            name='ValoracionesPeliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.IntegerField()),
                ('comentario', models.TextField()),
                ('fechaValoracion', models.DateTimeField(auto_now_add=True)),
                ('peliculaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.peliculas')),
                ('usuarioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='ValoracionesSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.IntegerField()),
                ('comentario', models.TextField()),
                ('fechaValoracion', models.DateTimeField(auto_now_add=True)),
                ('serieId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.series')),
                ('usuarioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.usuarios')),
            ],
        ),
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
