# Generated by Django 4.2.7 on 2023-11-27 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_actoresyactrices_directores_episodios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodios',
            name='serieId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.series'),
        ),
        migrations.AlterField(
            model_name='facturacion',
            name='usuarioId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.usuarios'),
        ),
        migrations.AlterField(
            model_name='playlists',
            name='usuarioId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.usuarios'),
        ),
        migrations.AlterField(
            model_name='valoracionespeliculas',
            name='peliculaId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.peliculas'),
        ),
        migrations.AlterField(
            model_name='valoracionespeliculas',
            name='usuarioId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.usuarios'),
        ),
        migrations.AlterField(
            model_name='valoracionesseries',
            name='serieId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.series'),
        ),
        migrations.AlterField(
            model_name='valoracionesseries',
            name='usuarioId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.usuarios'),
        ),
    ]
